In [104]:
import numpy as np
import scipy as sp
import sympy as smp

# Test for irreducability in a representation

- Take a representation (group elements mapped to matricies -> array of matricies built from generators)
    - generators -> array of matricies p(g) w/ dimension n

- Find the commutant of the representation (the set of matricies that commutes w/ the representation -> another array of matricies)
    - build commuting condition
    - for every generator g, calculate $M_g = I \otimes p(g) - p(g)^T \otimes I$
        - This encodes the idea of commutation into M_g for every generator g
    - Stack all of the M_g's into a tall matrix M

- Find the dimension of the commutant, and it will tell you if the representation is irreducable (dim Com = 1) or not -> compute nullity of the vectorized commutant
    - dim(Commutant) = nullity(M) = $n^2$ - rank(M)
        - dim(Comm) = 1 -> irreducable
        - dim(Comm) > 1 -> reducable

Consider the cyclic group $\mathbb{Z}_n$, the integers modulo n

This group only has a single generator, with every element being a power of that generator, shifting the basis by 1 cyclically. The representation is 
$$ \rho : G \to GL(V) $$
where $$V = \mathbb{C}^n$$

The single generator of this group is the element $1 \in \mathbb{Z}_n$, the abstract idea of 'add 1 mod n'. This element produces the rest of the elements

$\rho(1)$ is the matrix that the representation assigns to the generator, the cyclic shift generator shown below

In [105]:
# representation matrix of the single generator that generates every element of Zn
p1 = np.array([
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0]
]).astype(complex)

# for S3
s1 = np.array([
    [0, 1, 0],
    [1, 0, 0],
    [0, 0, 1]
]).astype(complex)
s2 = p1


# Z4, S4


Since every other element is generated by the same matrix 

(powers of $\rho, \rho(2) = \rho(1)^2, \rho(3) = \rho(1)^3$, etc.)

If a matrix commutes with $\rho(1)$, it commutes with every power.

In [106]:
generators = [p1]
n = p1.shape[0]
I = np.eye(n, dtype=complex)

# then calculate the vectorized commutant

M = np.vstack([np.kron(I, g) - np.kron(np.transpose(g), I) for g in generators], dtype=complex)

M

array([[ 0.+0.j,  0.+0.j,  1.+0.j, -1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
         0.+0.j,  0.+0.j],
       [ 1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j,
         0.+0.j,  0.+0.j],
       [ 0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j,
         0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j, -1.+0.j,
         0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
        -1.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j,
         0.+0.j, -1.+0.j],
       [-1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
         0.+0.j,  1.+0.j],
       [ 0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j,
         0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
         1.+0.j,  0.+0.j]])

dim Commutant = nullity(M) = $n^2$ - rank(M)

To get the dimension of the commutant, find the nullity of M, or the dimension of the nullspace/kernel of constraint matrix. -> $n^2$ is the dimension of the whole space of matricies (commuting or not), so to get the ones that commute, is the kernel of the matrix that tests the commuting property for all of the generators, as the one's that map to 0 commute. 

In [107]:
# now compute the nullity of M to find the dimension of the commutant
dimC = n**2 - np.linalg.matrix_rank(M)

print(f"The dimension of the commutant is {dimC}")
print(f"The representation is irreducible" * int(dimC==1))
print(f"The representation is reducible" * int(dimC!=1))


The dimension of the commutant is 3

The representation is reducible


Now try finding the eigenvectors to get invariant eigen-subspaces to calculate the dimension

In [108]:

# for Zn, use p1 (the permutation matrix)
p1, I

(array([[0.+0.j, 0.+0.j, 1.+0.j],
        [1.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j, 0.+0.j]]),
 array([[1.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j]]))

In [ ]:
# find the eigenvalues and eigenvectors
λ, v = np.linalg.eig(p1)

eigenbasis = [(λ[i], v[:, i]) for i in range(len(λ))]

# for basis in eigenbasis:
#     print(basis, "\n")

for basis in eigenbasis:
    print(f"λ: {basis[0]}\nv = {basis[1]}\n")

λ: (-0.5000000000000001+0.866025403784439j)
v = [-0.28867513+0.5j  0.57735027+0.j  -0.28867513-0.5j]

λ: (-0.5000000000000001-0.866025403784439j)
v = [-0.28867513-0.5j  0.57735027+0.j  -0.28867513+0.5j]

λ: (1+0j)
v = [0.57735027+0.00000000e+00j 0.57735027-3.18403659e-32j
 0.57735027-3.47876716e-32j]



In [122]:
pass_cond = 0
for basis in eigenbasis:
    # for every eigenvector

    v = basis[1]
    print(f"Eigenvector: {v}\n")

    for gen in generators:
        gv = gen @ v
        c = (v.conjugate() @ gv) / (v.conjugate() @ v)
        invariant = np.allclose(gv, c * v)
        pass_cond += int(invariant)

        print(f"ρ(g)v = {gv}")
        print(f"c = {c}")
        print(invariant * "Pass")

        print("-----------------")

print(((1 - (pass_cond == len(eigenbasis))) * "Not ") + "Invariant!")

Eigenvector: [-0.28867513+0.5j  0.57735027+0.j  -0.28867513-0.5j]

ρ(g)v = [-0.28867513-0.5j -0.28867513+0.5j  0.57735027+0.j ]
c = (-0.5+0.8660254037844386j)
Pass
-----------------
Eigenvector: [-0.28867513-0.5j  0.57735027+0.j  -0.28867513+0.5j]

ρ(g)v = [-0.28867513+0.5j -0.28867513-0.5j  0.57735027+0.j ]
c = (-0.5-0.8660254037844387j)
Pass
-----------------
Eigenvector: [0.57735027+0.00000000e+00j 0.57735027-3.18403659e-32j
 0.57735027-3.47876716e-32j]

ρ(g)v = [0.57735027-3.47876716e-32j 0.57735027+0.00000000e+00j
 0.57735027-3.18403659e-32j]
c = (1+5.4738221262688155e-48j)
Pass
-----------------
Invariant!


In [124]:
generators = [s1, s2]

def check_invariance(eigenbasis, label):
    print(f"=== Eigenvectors of {label} ===\n")
    for lam, v in eigenbasis:
        passed_all = True
        print(f"λ = {lam:.4f}\nv = {v}")
        for gen in generators:
            gv = gen @ v
            c = (v.conjugate() @ gv) / (v.conjugate() @ v)
            invariant = np.allclose(gv, c * v)
            passed_all &= invariant
            print(f"  ρ(g)v = {gv}")
            print(f"  c = {c:.4f} -> {'Pass' if invariant else 'Fail'}")
        print(f"  span(v) {'IS' if passed_all else 'is NOT'} invariant\n")

λ1, v1 = np.linalg.eig(s1)
λ2, v2 = np.linalg.eig(s2)

eigenbasis1 = [(λ1[i], v1[:, i]) for i in range(len(λ1))]
eigenbasis2 = [(λ2[i], v2[:, i]) for i in range(len(λ2))]

check_invariance(eigenbasis1, "s1")
check_invariance(eigenbasis2, "s2")

=== Eigenvectors of s1 ===

λ = 1.0000+0.0000j
v = [ 0.70710678-0.j  0.70710678+0.j -0.        -0.j]
  ρ(g)v = [0.70710678+0.j 0.70710678+0.j 0.        +0.j]
  c = 1.0000+0.0000j -> Pass
  ρ(g)v = [0.        +0.j 0.70710678+0.j 0.70710678+0.j]
  c = 0.5000+0.0000j -> Fail
  span(v) is NOT invariant

λ = -1.0000+0.0000j
v = [ 0.70710678+0.j -0.70710678-0.j -0.        -0.j]
  ρ(g)v = [-0.70710678+0.j  0.70710678+0.j  0.        +0.j]
  c = -1.0000+0.0000j -> Pass
  ρ(g)v = [ 0.        +0.j  0.70710678+0.j -0.70710678+0.j]
  c = -0.5000+0.0000j -> Fail
  span(v) is NOT invariant

λ = 1.0000+0.0000j
v = [0.+0.j 0.+0.j 1.+0.j]
  ρ(g)v = [0.+0.j 0.+0.j 1.+0.j]
  c = 1.0000+0.0000j -> Pass
  ρ(g)v = [1.+0.j 0.+0.j 0.+0.j]
  c = 0.0000+0.0000j -> Fail
  span(v) is NOT invariant

=== Eigenvectors of s2 ===

λ = -0.5000+0.8660j
v = [-0.28867513+0.5j  0.57735027+0.j  -0.28867513-0.5j]
  ρ(g)v = [ 0.57735027+0.j  -0.28867513+0.5j -0.28867513-0.5j]
  c = -0.0000+0.0000j -> Fail
  ρ(g)v = [-0.2886751